version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/chess.db:/app/chess.db
    environment:
      DATABASE_URL: sqlite:/app/chess.db
      CORS_ORIGIN: https://chess.rdevs.fr
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: unless-stopped
