services:
  backend:
    container_name: chess-backend
    build:
      context: ./backend
      dockerfile: dockerfile
    volumes:
      - db_data:/app/data
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CORS_ORIGIN: ${CORS_ORIGIN}
      RUST_LOG: info
    command: sh -lc "set -euo pipefail; mkdir -p /app/data && chmod 777 /app/data && sqlx migrate run -v && ./chess-backend"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: on-failure

  frontend:
    container_name: chess-frontend
    build:
      context: ./frontend
      dockerfile: dockerfile
      args:
        VITE_GRAPHQL_API_URL: /graphql
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
