version: "3.8"

services:
  backend:
    container_name: chess-backend
    image: chess-backend:local
    build:
      context: ./backend
      dockerfile: dockerfile
    volumes:
      - db_data:/app/data
    environment:
      DATABASE_URL: ${DATABASE_URL:-sqlite:///app/data/chess.db}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost}
      RUST_LOG: ${RUST_LOG:-info}
      RUST_BACKTRACE: ${RUST_BACKTRACE:-1}
    command: ./chess-backend
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped

  frontend:
    container_name: chess-frontend
    image: chess-frontend:local
    build:
      context: ./frontend
      dockerfile: dockerfile
      args:
        VITE_GRAPHQL_API_URL: /graphql
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db_data:
