
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - chess_db:/app/data
    environment:
      DATABASE_URL: "sqlite:///app/data/chess.db"
      CORS_ORIGIN: "https://chess.rdevs.fr"
      RUST_LOG: "debug"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_GRAPHQL_API_URL: "/graphql"
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  chess_db:
    driver: local
