version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/data:/app/data
    environment:
      DATABASE_URL: sqlite:/app/data/chess.db
      CORS_ORIGIN: https://chess.rdevs.fr
      RUST_LOG: debug
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: unless-stopped
